default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  Maintenance database: postgres
  username: postgres
  password: 12@34
  host: localhost
  port: 5432
  
development:
  <<: *default
  database: blog_app

test:
  <<: *default
  database: blog_app

production:
  <<: *default
  database: blog_app
  password: <%= ENV["BUDGET_APP_DATABASE_PASSWORD"] %>
  url: <%= ENV["DATABASE_URL"]%>